version: "3.5"

services:
  wallabag:
    container_name: wallabag
    hostname: wallabag
    image: wallabag/wallabag:2.6.14
    restart: on-failure:5
    expose:
      - 80
    environment:
      # GENERAL
      - TZ=Europe/Paris
      # NGINX + LETSENCRYPT
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${APP_DOMAIN}
      - LETSENCRYPT_HOST=${APP_DOMAIN}
      # APP
      - SYMFONY__ENV__FROM_EMAIL=${SYMFONY__ENV__FROM_EMAIL}
      - SYMFONY__ENV__DOMAIN_NAME=${SYMFONY__ENV__DOMAIN_NAME}
    volumes:
      - ./volumes/wallabag_images:/var/www/wallabag/web/assets/images
      - ./volumes/wallabag_data:/var/www/wallabag/data
    networks:
      - proxy

networks:
  proxy:
    external: true
