version: "3.5"

services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/home-operations/sonarr:4.0.18.2978@sha256:2cd77fb3d81909a734d61bb8f71462044cb9d2f187e626a28a05a5c4e4be8fd2
    cpu_count: 4
    mem_limit: 2G
    memswap_limit: 2G
    read_only: true
    user: ${PUID:?}:${PGID:?}
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:mode=770,noexec,size=10M,uid=${PUID:?},gid=${PGID:?}
    volumes:
      - ./volumes/config:/config
      - ~/files:/data
    healthcheck:
      test:
        - CMD
        - wget
        - --quiet
        - --timeout=3
        - --tries=1
        - --spider
        - http://localhost:8989/ping
      interval: 5s
      timeout: 4s
      retries: 4
      start_period: 5s
    environment:
      # General
      - TZ=Europe/Paris
      - PUID=${PUID:?}
      - PGID=${PGID:?}
      # NGINX + LETSENCRYPT
      - VIRTUAL_PORT=8989
      - VIRTUAL_HOST=${APP_DOMAIN:?}
      - LETSENCRYPT_HOST=${APP_DOMAIN:?}
      # NOTE: fix for read-only filesystems, see:
      #       https://stackoverflow.com/questions/74447989/failed-to-create-coreclr-hresult-0x80004005#comment131446515_74447989
      - COMPlus_EnableDiagnostics="0"
    networks:
      - proxy
      - arr

networks:
  proxy:
    external: true
  arr:
    external: true
