version: "3.5"

services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/home-operations/prowlarr:2.4.0.5391@sha256:91af7cbc8e357dede960033c9ecfb3a65e145d90d4e495e13adb2fbc6a546807
    restart: always
    cpu_count: 4
    mem_limit: 3G
    memswap_limit: 3G
    read_only: true
    cap_drop:
      - ALL
    user: ${PUID:?}:${PGID:?}
    tmpfs:
      - /tmp:mode=770,noexec,size=10M,uid=${PUID:?},gid=${PGID:?}
    healthcheck:
      test:
        - CMD
        - wget
        - --quiet
        - --timeout=3
        - --tries=1
        - --spider
        - http://localhost:9696/ping
      interval: 10s
      timeout: 5s
      retries: 8
      start_period: 15s
    environment:
      # General
      - TZ=Europe/Paris
      - PUID=${PUID:?}
      - PGID=${PUID:?}
      # NGINX + LETSENCRYPT
      - VIRTUAL_PORT=9696
      - VIRTUAL_HOST=${APP_DOMAIN:?}
      - LETSENCRYPT_HOST=${APP_DOMAIN:?}
      # APP
      # VPN
      - http_proxy=http://gluetun:8888
      - https_proxy=http://gluetun:8888
      - no_proxy=transmission,flaresolverr,sonarr,radarr,lidarr,readarr,bazarr,unpackerr,localhost,127.0.0.1
    volumes:
      - ./volumes/config:/config
      - ./volumes/blackhole:/blackhole
    networks:
      - proxy
      - vpn
      - arr

  flaresolverr:
    container_name: flaresolverr
    restart: always
    image: ghcr.io/flaresolverr/flaresolverr:v3.5.0@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47
    user: ${PUID:?}:${PGID:?}
    cpu_count: 4
    mem_limit: 6G
    memswap_limit: 6G
    environment:
      # General
      - TZ=Europe/Paris
      # APP
      # VPN
      - http_proxy=http://gluetun:8888
      - https_proxy=http://gluetun:8888
      - no_proxy=prowlarr,sonarr,radarr,lidarr,readarr,bazarr,unpackerr,localhost,127.0.0.1
    cap_drop:
      - ALL
    networks:
      - vpn

networks:
  proxy:
    external: true
  vpn:
    external: true
  arr:
    external: true
