version: "3.5"

services:
  it_tools:
    container_name: it_tools
    hostname: it_tools
    image: corentinth/it-tools:2024.10.22-7ca5933
    restart: on-failure:5
    environment:
      # General
      - TZ=Europe/Paris
      # nginx + letsencrypt
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${APP_DOMAIN}
      - LETSENCRYPT_HOST=${APP_DOMAIN}
    networks:
      - proxy

networks:
  proxy:
    external: true
