version: "3.5"

services:
  transmission:
    container_name: torrensearch
    image: ghcr.io/gmolveau/torrensearch-web:1.0.0
    restart: always
    environment:
      # General
      - TZ=Europe/Paris
      # NGINX + LETSENCRYPT
      - VIRTUAL_PORT=8000
      - VIRTUAL_HOST=${APP_DOMAIN}
      - LETSENCRYPT_HOST=${APP_DOMAIN}
      # APP
      - TORRENSEARCH_WEB_USER=${TORRENSEARCH_WEB_USER:?}
      - TORRENSEARCH_WEB_PASSWORD=${TORRENSEARCH_WEB_PASSWORD:?}
      # VPN
      - http_proxy=http://gluetun:8888
      - https_proxy=http://gluetun:8888
    volumes:
      - ./volumes/config:/config
    networks:
      - proxy
      - vpn

networks:
  proxy:
    external: true
  vpn:
    external: true
