version: "3.5"

services:
  seer:
    container_name: seer
    restart: always
    image: ghcr.io/seerr-team/seerr:v3.2.0@sha256:ff88bff83ef0ae51c57eb8eb8a5da8f015ec4de2ba6f6ef810d966eaae1d6f01
    user: ${PUID:?}:${PGID:?}
    init: true
    cpu_count: 2
    mem_limit: 1G
    memswap_limit: 1G
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:mode=770,noexec,size=50M,uid=${PUID:?},gid=${PGID:?}
    environment:
      # General
      - TZ=Europe/Paris
      - PUID=${PUID:?}
      - PGID=${PUID:?}
      # NGINX + LETSENCRYPT
      - VIRTUAL_PORT=5055
      - VIRTUAL_HOST=${APP_DOMAIN:?}
      - LETSENCRYPT_HOST=${APP_DOMAIN:?}
      # APP
    healthcheck:
      test:
        - CMD
        - wget
        - --quiet
        - --timeout=3
        - --tries=1
        - --spider
        - http://localhost:5055
      interval: 5s
      timeout: 4s
      retries: 4
      start_period: 5s
    volumes:
      - ./volumes/config:/config
    networks:
      - proxy
      - arr

networks:
  proxy:
    external: true
  arr:
    external: true
