version: "3.5"

services:
  nginx_proxy:
    container_name: nginx_proxy
    build:
      context: .
      dockerfile: nginx_proxy.dockerfile
    restart: on-failure:5
    ports:
      - "80:80"
      - "443:443"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./volumes/nginx_conf.d:/etc/nginx/conf.d
      - ./volumes/nginx_certs:/etc/nginx/certs:ro
      - ./volumes/nginx_vhost.d:/etc/nginx/vhost.d
      - ./volumes/nginx_dhparam:/etc/nginx/dhparam
      - ./volumes/nginx_htpasswd:/etc/nginx/htpasswd:ro
      - ./volumes/nginx_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro # NOTE, this container has access to docker socket (this is like root)
    networks:
      - proxy

  acme_companion:
    image: nginxproxy/acme-companion:2.5.2
    container_name: nginx_proxy_acme
    restart: on-failure:5
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - NGINX_PROXY_CONTAINER=nginx_proxy
    depends_on:
      - nginx_proxy
    volumes:
      - ./volumes/nginx_conf.d:/etc/nginx/conf.d
      - ./volumes/nginx_certs:/etc/nginx/certs:rw
      - ./volumes/nginx_vhost.d:/etc/nginx/vhost.d
      - ./volumes/nginx_html:/usr/share/nginx/html
      - ./volumes/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

networks:
  proxy:
    name: proxy
