version: "3.5"

services:
  lidarr:
    container_name: lidarr
    image: ghcr.io/home-operations/lidarr:3.1.5.5066@sha256:4919f82d018df539b2999e4bf8844d3907f95c2907e95da7d41c83b76d3f9cf6
    cpu_count: 4
    mem_limit: 2G
    memswap_limit: 2G
    read_only: true
    user: ${PUID:?}:${PGID:?}
    cap_drop:
      - ALL
    tmpfs:
      - /tmp:mode=770,noexec,size=10M,uid=${PUID:?},gid=${PGID:?}
    volumes:
      - ./volumes/config:/config
      - ~/files:/data
    healthcheck:
      test:
        - CMD
        - wget
        - --quiet
        - --timeout=3
        - --tries=1
        - --spider
        - http://localhost:8686/ping
      interval: 5s
      timeout: 4s
      retries: 4
      start_period: 5s
    environment:
      # General
      - TZ=Europe/Paris
      - PUID=${PUID:?}
      - PGID=${PGID:?}
      # NGINX + LETSENCRYPT
      - VIRTUAL_PORT=8686
      - VIRTUAL_HOST=${APP_DOMAIN:?}
      - LETSENCRYPT_HOST=${APP_DOMAIN:?}
      # NOTE: fix for read-only filesystems, see:
      #       https://stackoverflow.com/questions/74447989/failed-to-create-coreclr-hresult-0x80004005#comment131446515_74447989
      - COMPlus_EnableDiagnostics="0"
    networks:
      - proxy
      - arr

networks:
  proxy:
    external: true
  arr:
    external: true
