version: '3.5'

services:
  freshrss:
    container_name: freshrss
    hostname: freshrss
    image: linuxserver/freshrss
    restart: on-failure:5
    environment:
      # General
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      # nginx + letsencrypt
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${APP_DOMAIN}
      - LETSENCRYPT_HOST=${APP_DOMAIN}
      # app
      - CRON_MIN=*/10
    volumes:
      - freshrss_data:/config
    expose:
      - 80
    networks:
      - proxy

volumes:
  freshrss_data:
    name: freshrss_data

networks:
  proxy:
    external: true
