version: "3"

services:
  gluetun:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetun
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - gluetun:/gluetun
    environment:
      # General
      - TZ=Europe/Paris
      # App
      - HTTPPROXY=${HTTPPROXY:-on}
      # HTTPPROXY exposed on port 8888 by default
      - HTTPPROXY_STEALTH=${HTTPPROXY_STEALTH:-off}
      - HTTPPROXY_LOG=${HTTPPROXY_LOG:-off}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      # See https://github.com/qdm12/gluetun-wiki/issues/15
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CATEGORIES=${SERVER_CATEGORIES}
      # Timezone for accurate log times
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
    networks:
      - vpn

volumes:
  gluetun:
    name: gluetun

networks:
  vpn:
    driver: bridge
    name: vpn
