version: "3.5"

services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission:4.0.6
    restart: always
    environment:
      # General
      - TZ=Europe/Paris
      # NGINX + LETSENCRYPT
      - VIRTUAL_PORT=9091
      - VIRTUAL_HOST=${APP_DOMAIN}
      - LETSENCRYPT_HOST=${APP_DOMAIN}
      # APP
      - USER=${WEBUI_USER}
      - PASS=${WEBUI_PASS}
      # VPN
      - http_proxy=http://gluetun:8888
      - https_proxy=http://gluetun:8888
    networks:
      - proxy
      - vpn

networks:
  proxy:
    external: true
  vpn:
    external: true
