version: '3.5'

services:
  nitter:
    container_name: nitter
    hostname: nitter
    image: zedeus/nitter:latest
    restart: on-failure:5
    expose:
      - 8080
    env:
      - TZ=Europe/Paris
      # NGINX + LETSENCRYPT
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=${APP_DOMAIN}
      - LETSENCRYPT_HOST=${APP_DOMAIN}
    networks:
      - proxy

networks:
  proxy:
    external: true
